steps:
  # This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/github.com/vigostudio/overlay-client:$SHORT_SHA'
  - 'overlay-client/'

- name: 'gcr.io/cloud-builders/docker'
  id: Build2
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/github.com/vigostudio/overlay-client:$SHORT_SHA'
  - 'overlay-server/'

# This step pushes the image to Container Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/github.com/vigostudio/overlay-server:$SHORT_SHA'
- name: 'gcr.io/cloud-builders/docker'
  id: Push2
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/github.com/vigostudio/overlay-server:$SHORT_SHA'


# - name: 'gcr.io/cloud-builders/kubectl'
#   id: Deploy
#   args:
#   - 'apply'
#   - '-f'
#   - 'kubernetes.yaml'
#   env:
#   - 'CLOUDSDK_COMPUTE_ZONE=us-central1-b'
#   - 'CLOUDSDK_CONTAINER_CLUSTER=hello-cloudbuild'
